#!/usr/bin/sh
# @author nate zhou
# @since 2025
# river/autostart

# -q: quiet, don"t print errors
killall -q swaybg fcitx5 notifyd.sh dam

riverctl spawn "$SCRIPT_HOME/bgimg-random.sh"

riverctl spawn "$SCRIPT_HOME/foot-server.sh"
riverctl spawn "$SCRIPT_HOME/notifyd.sh"

# start if not running
riverctl spawn "$SCRIPT_HOME/std/std-dambar.sh | dam"

pgrep "swayidle" || riverctl spawn "swayidle"

#pgrep -f "wl-paste --watch cliphist store" || riverctl spawn "wl-paste --watch cliphist store"

pgrep "mako" || riverctl spawn "mako"

riverctl spawn "fcitx5 -d"
