#!/usr/bin/sh
# @author nate zhou
# @since 2025
# river/autostart

# -q: quiet, don"t print errors
killall -q swaybg notifyd.sh waybar

riverctl spawn "$SCRIPT_HOME/bgimg-random.sh"

riverctl spawn "$SCRIPT_HOME/foot-server.sh"
riverctl spawn "$SCRIPT_HOME/notifyd.sh"
riverctl spawn waybar
# start if not running
#riverctl spawn "$SCRIPT_HOME/dam.sh"

pgrep "swayidle" || riverctl spawn "swayidle"

#pgrep -f "wl-paste --watch cliphist store" || riverctl spawn "wl-paste --watch cliphist store"

pgrep "mako" || riverctl spawn "mako"

pgrep "fcitx5" || fcitx5 -d
