#!/usr/bin/sh
# @author nate zhou
# @since 2025
# river/bindings

mod=Mod4    # Mod1=Alt, Mod4=Super
#wobfifo="/tmp/wob.fifo"
term="footclient"

# basic
riverctl map normal ${mod}+Shift r spawn "$HOME/.config/river/init"

riverctl map normal $mod Return spawn $term

riverctl map normal Control+Shift Return spawn "footclient -T Scratchpad_Tmux $HOME/.local/bin/tmuxd"

riverctl map normal $mod c spawn "firefox"

riverctl map normal $mod d spawn "wmenu-run -f 'FiraCodeNerdFont Bold 11' -S '#bb9fff' -n '#555555' -s '#000000'"

riverctl map -release normal ${mod}+Shift+Control l spawn "swaylock"

riverctl map normal ${mod}+Shift+Control h spawn "$HOME/.local/bin/swayhibe"

riverctl map normal ${mod}+Shift p exit

riverctl map normal None Caps_Lock spawn "$HOME/.local/bin/capslock"

#riverctl map normal $mod n spawn "dunstctl close"
#riverctl map normal ${mod}+Shift n spawn "dunstctl history-pop"

riverctl map normal $mod F1 spawn "$SCRIPT_HOME/media-control/volume-control.sh mute"
riverctl map -repeat normal $mod F2 spawn "$SCRIPT_HOME/media-control/volume-control.sh down"
riverctl map -repeat normal $mod F3 spawn "$SCRIPT_HOME/media-control/volume-control.sh up"

riverctl map -repeat normal $mod F5 spawn "$SCRIPT_HOME/media-control/brightness-control.sh down"
riverctl map -repeat normal $mod F6 spawn "$SCRIPT_HOME/media-control/brightness-control.sh up"

# windows management
riverctl map -release normal ${mod} q close

riverctl map normal $mod f toggle-fullscreen
riverctl map normal ${mod}+Shift space toggle-float

# window navigation
riverctl map normal $mod j focus-view next
riverctl map normal $mod k focus-view previous

# window movement
riverctl map normal ${mod}+Shift j swap next
riverctl map normal ${mod}+Shift k swap previous

# shift tags
#riverctl map normal $mod Period spawn "river-shifttags --occupied"
#riverctl map normal $mod Comma spawn "river-shifttags --shift -1 --occupied"

# workspace navigation
riverctl map normal ${mod}+Control Period focus-output next
riverctl map normal ${mod}+Control Comma focus-output previous

# workspace movement
riverctl map normal ${mod}+Shift Period send-to-output next
riverctl map normal ${mod}+Shift Comma send-to-output previous

# bring focus to the top of the layout stack
riverctl map normal $mod z zoom

# move floating window
riverctl map normal $mod y move left 100
riverctl map normal $mod u move down 100
riverctl map normal $mod i move up 100
riverctl map normal $mod o move right 100

# resize views
riverctl map normal ${mod}+Shift y resize horizontal -100
riverctl map normal ${mod}+Shift u resize vertical 100
riverctl map normal ${mod}+Shift i resize vertical -100
riverctl map normal ${mod}+Shift o resize horizontal 100

# mouse
riverctl map-pointer normal $mod BTN_LEFT move-view
riverctl map-pointer normal $mod BTN_RIGHT resize-view
riverctl map-pointer normal $mod BTN_MIDDLE toggle-float

# all tags
all_tags=$(((1 << 32) - 1))
riverctl map normal $mod 0 set-focused-tags $all_tags
riverctl map normal ${mod}+Shift 0 set-view-tags $all_tags

riverctl map normal $mod tab focus-previous-tags
