#!/usr/bin/sh
# @author nate zhou
# @modifier sc
# @since 2025

. $HOME/.config/river/autostart
. $HOME/.config/river/bindings
#. $HOME/.config/river/modes
. $HOME/.config/river/rivertile

# remap key
#riverctl keyboard-layout-file "$HOME/.config/layout.xkb"

# display
wlr-randr --output eDP-1 --scale 1.5
# input HZ, ms
riverctl set-repeat 30 300

riverctl hide-cursor timeout 5000
riverctl hide-cursor when-typing enabled

# enable tap-to-click for touchpads
for i in $(riverctl list-inputs | grep -i touchpad); do
    riverctl input "$i" tap enabled
done

# border
riverctl border-color-focused 0xf44d40 # tomato red
riverctl border-color-unfocused 0x333333 # dark gray
riverctl border-width 2

# window rules
riverctl rule-add -app-id "*" ssd # Server-Side Decorations（服务端装饰）
riverctl rule-add -app-id "file-*" float # GIMP file import/export
riverctl rule-add -app-id "script-fu" float # GIMP gegl operations

# tags
for i in $(seq 1 9)
do
    tags=$((1 << ($i - 1)))
    riverctl map normal $mod $i set-focused-tags $tags
    riverctl map normal ${mod}+Shift $i set-view-tags $tags
    riverctl map normal Control $i toggle-focused-tags $tags
    riverctl map normal ${mod}+Control $i toggle-view-tags $tags
done

# scratchpad
# The scratchpad will live on an unused tag. Which tags are used depends on your
# config, but rivers default uses the first 9 tags.
scratch_tag=$((1 << 20 ))

# Toggle the scratchpad
riverctl map normal $mod s toggle-focused-tags ${scratch_tag}

# Send windows to the scratchpad
riverctl map normal ${mod}+Shift s set-view-tags ${scratch_tag}

# Set spawn tagmask to ensure new windows don't have the scratchpad tag unless
# explicitly set.
all_but_scratch_tag=$(( ((1 << 32) - 1) ^ $scratch_tag ))
riverctl spawn-tagmask ${all_but_scratch_tag}
